
services:
  mariadb:
    container_name: mariadb
    image: mariadb:perso
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:perso
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress:perso
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:perso
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  ftp:
    container_name: ftp
    image: ftp:perso
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/ftpuser/ftp
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME}
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME}

networks:
  inception:
    name: inception
    driver: bridge
